In [22]:
import os
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold
import pandas as pd

fileLoc = 'trainDataMovieReviews.csv'
movieData = pd.read_csv(fileLoc)

corpus = []
for desc in movieData['review']:
    corpus.append(desc)
#Stratified 10-cross fold validation with SVM and Multinomial NB 

labels = movieData.iloc[:,-1]
labels = labels.tolist()
for i in range(len(labels)):
    if (labels[i] == 'pos'):
        labels[i] = 1
    if (labels[i] == 'neg'):
        labels[i] = -1
        
labels = np.array(labels)
       
kf = StratifiedKFold(n_splits=10)
 
totalsvm = 0           # Accuracy measure on 2000 files
totalNB = 0
totalMatSvm = np.zeros((2,2));  # Confusion matrix on 2000 files
totalMatNB = np.zeros((2,2));
 
for train_index, test_index in kf.split(corpus,labels):
    X_train = [corpus[i] for i in train_index]
    X_test = [corpus[i] for i in test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    vectorizer = TfidfVectorizer(min_df=5, max_df = 0.6, sublinear_tf=True, use_idf=True,stop_words='english')
    train_corpus_tf_idf = vectorizer.fit_transform(X_train) 
    test_corpus_tf_idf = vectorizer.transform(X_test)
     
    model1 = LinearSVC()
    model2 = MultinomialNB()    
    model1.fit(train_corpus_tf_idf,y_train)
    model2.fit(train_corpus_tf_idf,y_train)
    result1 = model1.predict(test_corpus_tf_idf)
    result2 = model2.predict(test_corpus_tf_idf)
     
    totalMatSvm = totalMatSvm + confusion_matrix(y_test, result1)
    totalMatNB = totalMatNB + confusion_matrix(y_test, result2)
    totalsvm = totalsvm+sum(y_test==result1)
    totalNB = totalNB+sum(y_test==result2)
     
print(totalMatSvm, totalsvm/25000.0, totalMatNB, totalNB/25000.0)

KeyboardInterrupt: 

In [13]:
print(result1)

[1 0 0 ... 0 1 0]


In [14]:
print(totalMatSvm)

[[10750.  1750.]
 [ 2071. 10429.]]


In [18]:
print(result2)

[1 0 0 ... 0 1 1]


In [19]:
print(totalMatNB)

[[10648.  1852.]
 [ 2732.  9768.]]


In [21]:
pd.read_csv(testset)

numpy.ndarray